version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_PREDICTION_URL=http://localhost:8001
    depends_on:
      - user-service
      - prediction-service

  user-service:
    build: ./backend/user_service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto
      - JWT_SECRET=your-secret-key
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  prediction-service:
    build: ./backend/prediction_service
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
      - COINGECKO_API_URL=https://api.coingecko.com/api/v3
    depends_on:
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: 