version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_PREDICTION_URL=http://localhost:8001
    depends_on:
      - user-service
      - prediction-service

  user-service:
    build: ./backend/user_service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto
      - JWT_SECRET=your-secret-key
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  prediction-service:
    build: ./backend/prediction_service
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
      - COINGECKO_API_URL=https://api.coingecko.com/api/v3
    depends_on:
      - redis

  notification-service:
    build: ./backend/notification_service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb://mongo:27017/crypto
      - REDIS_URL=redis://redis:6379
      - PRICE_API_URL=http://prediction-service:8001/api/price
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=noreply@cryptoapp.com
    depends_on:
      - mongo
      - redis
      - prediction-service
      - user-service

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: 